language: node_js
node_js:
  - "7"
  - "6"

cache:
  directories:
    - "node_modules"

before_install:
  - openssl aes-256-cbc -K $encrypted_d1d5f850c97f_key -iv $encrypted_d1d5f850c97f_iv -in deploy-key.enc -out ../deploy-key -d

install:
  - npm install

script:
  - npm test
  - ls

after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials

deploy:
  provider: script
  skip_cleanup: true
  script: "./bin/build_docs.sh"
  on:
    branch: master