export const Syntax = {
  int: "int",
  string: "string",
  decimal: "decimal",
  variable: "let",
  colon: ":",
  forwardSlash: "/",
  backwardSlash: "\\",
  rightBace: "{",
  leftBrace: "}",
  leftParen: "(",
  rightParen: ")",
  function: "fn",
  if: "if",
  else: "else",
  return: "return",
  equals: "=",
  quote: '"',
} as const;
