export var TokenType;
(function (TokenType) {
    TokenType[TokenType["PAREN_START"] = 0] = "PAREN_START";
    TokenType[TokenType["PAREN_END"] = 1] = "PAREN_END";
    TokenType[TokenType["IDENTIFIER"] = 2] = "IDENTIFIER";
    TokenType[TokenType["OPERATOR"] = 3] = "OPERATOR";
    TokenType[TokenType["END"] = 4] = "END";
    TokenType[TokenType["STRING"] = 5] = "STRING";
    TokenType[TokenType["ASSIGNMENT"] = 6] = "ASSIGNMENT";
    TokenType[TokenType["VARIABLE"] = 7] = "VARIABLE";
    TokenType[TokenType["NUMBER"] = 8] = "NUMBER";
    TokenType[TokenType["DECIMAL"] = 9] = "DECIMAL";
    TokenType[TokenType["IF"] = 10] = "IF";
    TokenType[TokenType["START_BRACE"] = 11] = "START_BRACE";
    TokenType[TokenType["END_BRACE"] = 12] = "END_BRACE";
    TokenType[TokenType["NONE"] = 13] = "NONE";
    TokenType[TokenType["ELSE"] = 14] = "ELSE";
    TokenType[TokenType["SEPARATOR"] = 15] = "SEPARATOR";
    TokenType[TokenType["FUNCTION_DECLARATION"] = 16] = "FUNCTION_DECLARATION";
    TokenType[TokenType["RETURN"] = 17] = "RETURN";
    TokenType[TokenType["TYPE_DECLARATION"] = 18] = "TYPE_DECLARATION";
})(TokenType || (TokenType = {}));
